In [40]:
from sklearn.datasets import fetch_openml

import pandas as pd

# 1.从OpenML加载数据集,指定名称为 "house_prices"
# 设置 as_frame=True 可以直接获得pandas的DataFrame,方便查看和操作
ames = fetch_openml(name="house_prices", as_frame=True) ## 返回Bunch对象

In [41]:
## 0.  查看Bunch对象的属性
"""
data: 特征数据矩阵,通常是一个二维 NumPy 数组,形状为 (n_samples, n_features)。

target: 目标标签数组,是一个一维 NumPy 数组,代表每个样本的分类结果。

feature_names: 特征名称列表,描述了每一列数据代表的含义

target_names: 标签类别名称列表

DESCR: 数据集的完整描述文本,包含来源、特征统计等信息。

"""
# ames.keys() # 查看字段
# print(ames.DESCR)
# print(ames.feature_names)
ames.data.head(5)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal

#### 选择部分特征列作为本次demo的输入

*   **MSSubClass**: 标识销售中涉及的住宅类型。
    *   20: 一层住宅 (1946年及以后,所有风格)
    *   30: 一层住宅 (1945年及以前)
    *   40: 一层带装修阁楼 (所有年代)
    *   45: 一层半 - 未装修 (所有年代)
    *   50: 一层半 - 已装修 (所有年代)
    *   60: 两层住宅 (1946年及以后)
    *   70: 两层住宅 (1945年及以前)
    *   75: 两层半住宅 (所有年代)
    *   80: 错层或多层
    *   85: 错层门厅
    *   90: 复式住宅 - 所有风格和年代
    *   120: 一层 PUD (规划单元开发) - (1946年及以后)
    *   150: 一层半 PUD - (所有年代)
    *   160: 两层 PUD - (1946年及以后)
    *   180: PUD - 多层 - 包括错层/门厅
    *   190: 双户改造 - 所有风格和年代
*   **LotArea**: 地块面积 (平方英尺)
*   **OverallCond**: 评估房屋的整体状况

In [47]:
# 1. 数据预处理
X: pd.DataFrame = ames.data
Y = ames.target

## 1.1 特征筛选
X = X[['MSSubClass','LotArea','OverallCond']]

## 1.2 去除重复项
keep_mask = ~X.duplicated(keep='first')
X = X[keep_mask]
Y = Y[keep_mask]
X.head(3)

   MSSubClass  LotArea  OverallCond
0          60     8450            5
1          20     9600            8
2          60    11250            5

In [43]:
# 3. 划分数据集
from sklearn.model_selection import train_test_split
# 指定随机数种子,方便复现
SEED = 42

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=SEED)

In [44]:
# 4.特征工程 - 标准化处理
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [45]:
# 5. 实例化线性回归模型
from sklearn.linear_model import LinearRegression
lr_estimator = LinearRegression(fit_intercept=True)
# 6. 模型训练
lr_estimator.fit(X_train, y_train)
# 6. 模型预测
y_pred = lr_estimator.predict(X_test)
# 7. 模型评估
from sklearn.metrics import mean_squared_error, mean_absolute_error
print(f'mean_absolute_error:{mean_absolute_error(y_test, y_pred)}')
print(f'mean_squared_error:{mean_squared_error(y_test, y_pred)}')

mean_absolute_error:54252.750087690554
mean_squared_error:6326300411.945458

In [46]:
#